// Generated by scripts/reference-data/build-external-resource-data.mjs
export default {
  "schemaVersion": 1,
  "checkedAt": "2026-10-08T01:36:49.240Z",
  "organisms": [
    {
      "common": "Human",
      "taxId": "9606",
      "name": "Homo sapiens",
      "label": "Human — Homo sapiens",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "homo_sapiens"
    },
    {
      "common": "Mouse",
      "taxId": "10090",
      "name": "Mus musculus",
      "label": "Mouse — Mus musculus",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "mus_musculus"
    },
    {
      "common": "Rat",
      "taxId": "10116",
      "name": "Rattus norvegicus",
      "label": "Rat — Rattus norvegicus",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "rattus_norvegicus"
    },
    {
      "common": "Cow",
      "taxId": "9913",
      "name": "Bos taurus",
      "label": "Cow — Bos taurus",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "bos_taurus"
    },
    {
      "common": "Dog",
      "taxId": "9615",
      "name": "Canis lupus familiaris",
      "label": "Dog — Canis lupus familiaris",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "canis_lupus_familiaris"
    },
    {
      "common": "Zebrafish",
      "taxId": "7955",
      "name": "Danio rerio",
      "label": "Zebrafish — Danio rerio",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "danio_rerio"
    },
    {
      "common": "Fruit fly",
      "taxId": "7227",
      "name": "Drosophila melanogaster",
      "label": "Fruit fly — Drosophila melanogaster",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "Budding yeast",
      "taxId": "4932",
      "name": "Saccharomyces cerevisiae",
      "label": "Budding yeast — Saccharomyces cerevisiae",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "Thale cress",
      "taxId": "3702",
      "name": "Arabidopsis thaliana",
      "label": "Thale cress — Arabidopsis thaliana",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "E. coli",
      "taxId": "562",
      "name": "Escherichia coli",
      "label": "E. coli — Escherichia coli",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "Pig",
      "taxId": "9823",
      "name": "Sus scrofa",
      "label": "Pig — Sus scrofa",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "sus_scrofa"
    },
    {
      "common": "Chicken",
      "taxId": "9031",
      "name": "Gallus gallus",
      "label": "Chicken — Gallus gallus",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "gallus_gallus"
    },
    {
      "common": "Sheep",
      "taxId": "9940",
      "name": "Ovis aries",
      "label": "Sheep — Ovis aries",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "species": "ovis_aries"
    },
    {
      "common": "C. elegans",
      "taxId": "6239",
      "name": "Caenorhabditis elegans",
      "label": "C. elegans — Caenorhabditis elegans",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "Maize",
      "taxId": "4577",
      "name": "Zea mays",
      "label": "Maize — Zea mays",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "E. coli K-12 MG1655",
      "taxId": "511145",
      "name": "Escherichia coli str. K-12 substr. MG1655",
      "label": "E. coli K-12 MG1655 — Escherichia coli str. K-12 substr. MG1655",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "Yeast S288C",
      "taxId": "559292",
      "name": "Saccharomyces cerevisiae S288C",
      "label": "Yeast S288C — Saccharomyces cerevisiae S288C",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    },
    {
      "common": "B. subtilis 168",
      "taxId": "224308",
      "name": "Bacillus subtilis subsp. subtilis str. 168",
      "label": "B. subtilis 168 — Bacillus subtilis subsp. subtilis str. 168",
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z"
    }
  ],
  "assemblies": [
    {
      "source": "ensembl",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "GRCh38",
      "name": "GRCh38.p14",
      "species": "homo_sapiens",
      "label": "Human — GRCh38.p14",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/homo_sapiens?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:11.455Z"
    },
    {
      "source": "ncbi",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "GCF_000001405.40",
      "name": "GRCh38.p14",
      "label": "Human — GRCh38.p14 (GCF_000001405.40)",
      "organism": "Homo sapiens",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9606/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:10.165Z"
    },
    {
      "source": "ucsc",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "hs1",
      "name": "Jan. 2022 (T2T CHM13v2.0/hs1)",
      "label": "Human — Jan. 2022 (T2T CHM13v2.0/hs1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "hg38",
      "name": "Dec. 2013 (GRCh38/hg38)",
      "label": "Human — Dec. 2013 (GRCh38/hg38)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z",
      "preferred": true
    },
    {
      "source": "ucsc",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "hg19",
      "name": "Feb. 2009 (GRCh37/hg19)",
      "label": "Human — Feb. 2009 (GRCh37/hg19)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "hg18",
      "name": "Mar. 2006 (NCBI36/hg18)",
      "label": "Human — Mar. 2006 (NCBI36/hg18)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "hg17",
      "name": "May 2004 (NCBI35/hg17)",
      "label": "Human — May 2004 (NCBI35/hg17)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9606",
      "assemblyTaxId": "9606",
      "id": "hg16",
      "name": "July 2003 (NCBI34/hg16)",
      "label": "Human — July 2003 (NCBI34/hg16)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "GRCm39",
      "name": "GRCm39",
      "species": "mus_musculus",
      "label": "Mouse — GRCm39",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/mus_musculus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:16.972Z"
    },
    {
      "source": "ncbi",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "GCF_000001635.27",
      "name": "GRCm39",
      "label": "Mouse — GRCm39 (GCF_000001635.27)",
      "organism": "Mus musculus",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/10090/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:12.065Z"
    },
    {
      "source": "ucsc",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "mm39",
      "name": "Jun. 2020 (GRCm39/mm39)",
      "label": "Mouse — Jun. 2020 (GRCm39/mm39)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z",
      "preferred": true
    },
    {
      "source": "ucsc",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "mm10",
      "name": "Dec. 2011 (GRCm38/mm10)",
      "label": "Mouse — Dec. 2011 (GRCm38/mm10)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "mm9",
      "name": "July 2007 (NCBI37/mm9)",
      "label": "Mouse — July 2007 (NCBI37/mm9)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "mm8",
      "name": "Feb. 2006 (NCBI36/mm8)",
      "label": "Mouse — Feb. 2006 (NCBI36/mm8)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10090",
      "assemblyTaxId": "10090",
      "id": "mm7",
      "name": "Aug. 2005 (NCBI35/mm7)",
      "label": "Mouse — Aug. 2005 (NCBI35/mm7)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "GRCr8",
      "name": "GRCr8",
      "species": "rattus_norvegicus",
      "label": "Rat — GRCr8",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/rattus_norvegicus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:18.378Z"
    },
    {
      "source": "ncbi",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "GCF_036323735.1",
      "name": "GRCr8",
      "label": "Rat — GRCr8 (GCF_036323735.1)",
      "organism": "Rattus norvegicus",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/10116/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:17.560Z"
    },
    {
      "source": "ucsc",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "rn8",
      "name": "Jan. 2024 (GRCr8/rn8)",
      "label": "Rat — Jan. 2024 (GRCr8/rn8)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "rn7",
      "name": "Nov. 2020 (mRatBN7.2/rn7)",
      "label": "Rat — Nov. 2020 (mRatBN7.2/rn7)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "rn6",
      "name": "Jul. 2014 (RGSC 6.0/rn6)",
      "label": "Rat — Jul. 2014 (RGSC 6.0/rn6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "rn5",
      "name": "Mar. 2012 (RGSC 5.0/rn5)",
      "label": "Rat — Mar. 2012 (RGSC 5.0/rn5)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "rn4",
      "name": "Nov. 2004 (Baylor 3.4/rn4)",
      "label": "Rat — Nov. 2004 (Baylor 3.4/rn4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "10116",
      "assemblyTaxId": "10116",
      "id": "rn3",
      "name": "June 2003 (Baylor 3.1/rn3)",
      "label": "Rat — June 2003 (Baylor 3.1/rn3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "ARS-UCD2.0",
      "name": "ARS-UCD2.0",
      "species": "bos_taurus",
      "label": "Cow — ARS-UCD2.0",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/bos_taurus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:22.186Z"
    },
    {
      "source": "ncbi",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "GCF_002263795.3",
      "name": "ARS-UCD2.0",
      "label": "Cow — ARS-UCD2.0 (GCF_002263795.3)",
      "organism": "Bos taurus",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9913/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:19.571Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "ARS_UCD2.0",
      "name": "Jul. 2023 (ARS-UCD2.0/GCF_002263795.3)",
      "label": "Cow — Jul. 2023 (ARS-UCD2.0/GCF_002263795.3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau9",
      "name": "Apr. 2018 (ARS-UCD1.2/bosTau9)",
      "label": "Cow — Apr. 2018 (ARS-UCD1.2/bosTau9)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau8",
      "name": "Jun. 2014 (Bos_taurus_UMD_3.1.1/bosTau8)",
      "label": "Cow — Jun. 2014 (Bos_taurus_UMD_3.1.1/bosTau8)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau7",
      "name": "Oct. 2011 (Baylor Btau_4.6.1/bosTau7)",
      "label": "Cow — Oct. 2011 (Baylor Btau_4.6.1/bosTau7)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau6",
      "name": "Nov. 2009 (Bos_taurus_UMD_3.1/bosTau6)",
      "label": "Cow — Nov. 2009 (Bos_taurus_UMD_3.1/bosTau6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau4",
      "name": "Oct. 2007 (Baylor 4.0/bosTau4)",
      "label": "Cow — Oct. 2007 (Baylor 4.0/bosTau4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau3",
      "name": "Aug. 2006 (Baylor 3.1/bosTau3)",
      "label": "Cow — Aug. 2006 (Baylor 3.1/bosTau3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9913",
      "assemblyTaxId": "9913",
      "id": "bosTau2",
      "name": "Mar. 2005 (Baylor 2.0/bosTau2)",
      "label": "Cow — Mar. 2005 (Baylor 2.0/bosTau2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "ROS_Cfam_1.0",
      "name": "ROS_Cfam_1.0",
      "species": "canis_lupus_familiaris",
      "label": "Dog — ROS_Cfam_1.0",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/canis_lupus_familiaris?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:24.682Z"
    },
    {
      "source": "ncbi",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "GCF_011100685.1",
      "name": "UU_Cfam_GSD_1.0",
      "label": "Dog — UU_Cfam_GSD_1.0 (GCF_011100685.1)",
      "organism": "Canis lupus familiaris",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9615/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:22.589Z"
    },
    {
      "source": "ucsc",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "canFam6",
      "name": "Oct. 2020 (Dog10K_Boxer_Tasha/canFam6)",
      "label": "Dog — Oct. 2020 (Dog10K_Boxer_Tasha/canFam6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "canFam5",
      "name": "May 2019 (UMICH_Zoey_3.1/canFam5)",
      "label": "Dog — May 2019 (UMICH_Zoey_3.1/canFam5)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "canFam4",
      "name": "Mar. 2020 (UU_Cfam_GSD_1.0/canFam4)",
      "label": "Dog — Mar. 2020 (UU_Cfam_GSD_1.0/canFam4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "canFam3",
      "name": "Sep. 2011 (Broad CanFam3.1/canFam3)",
      "label": "Dog — Sep. 2011 (Broad CanFam3.1/canFam3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "canFam2",
      "name": "May 2005 (Broad/canFam2)",
      "label": "Dog — May 2005 (Broad/canFam2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9615",
      "assemblyTaxId": "9615",
      "id": "canFam1",
      "name": "July 2004 (Broad/canFam1)",
      "label": "Dog — July 2004 (Broad/canFam1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "GRCz11",
      "name": "GRCz11",
      "species": "danio_rerio",
      "label": "Zebrafish — GRCz11",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/danio_rerio?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:26.706Z"
    },
    {
      "source": "ncbi",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "GCF_052040795.2",
      "name": "GRCz13ab",
      "label": "Zebrafish — GRCz13ab (GCF_052040795.2)",
      "organism": "Danio rerio",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/7955/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:24.982Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "GRCz12ab",
      "name": "Aug. 2025 (GRCz12ab/GCA_052040795.1)",
      "label": "Zebrafish — Aug. 2025 (GRCz12ab/GCA_052040795.1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "GRCz12tu",
      "name": "Apr. 2025 (GRCz12tu/GCF_049306965.1)",
      "label": "Zebrafish — Apr. 2025 (GRCz12tu/GCF_049306965.1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer11",
      "name": "May 2017 (GRCz11/danRer11)",
      "label": "Zebrafish — May 2017 (GRCz11/danRer11)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer10",
      "name": "Sep. 2014 (GRCz10/danRer10)",
      "label": "Zebrafish — Sep. 2014 (GRCz10/danRer10)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer7",
      "name": "Jul. 2010 (Zv9/danRer7)",
      "label": "Zebrafish — Jul. 2010 (Zv9/danRer7)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer6",
      "name": "Dec. 2008 (Zv8/danRer6)",
      "label": "Zebrafish — Dec. 2008 (Zv8/danRer6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer5",
      "name": "July 2007 (Zv7/danRer5)",
      "label": "Zebrafish — July 2007 (Zv7/danRer5)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer4",
      "name": "Mar. 2006 (Zv6/danRer4)",
      "label": "Zebrafish — Mar. 2006 (Zv6/danRer4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7955",
      "assemblyTaxId": "7955",
      "id": "danRer3",
      "name": "May 2005 (Zv5/danRer3)",
      "label": "Zebrafish — May 2005 (Zv5/danRer3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ncbi",
      "taxId": "7227",
      "assemblyTaxId": "7227",
      "id": "GCF_000001215.4",
      "name": "Release 6 plus ISO1 MT",
      "label": "Fruit fly — Release 6 plus ISO1 MT (GCF_000001215.4)",
      "organism": "Drosophila melanogaster",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/7227/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:27.197Z"
    },
    {
      "source": "ucsc",
      "taxId": "7227",
      "assemblyTaxId": "7227",
      "id": "dm6",
      "name": "Aug. 2014 (BDGP Release 6 + ISO1 MT/dm6)",
      "label": "Fruit fly — Aug. 2014 (BDGP Release 6 + ISO1 MT/dm6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7227",
      "assemblyTaxId": "7227",
      "id": "dm3",
      "name": "Apr. 2006 (BDGP R5/dm3)",
      "label": "Fruit fly — Apr. 2006 (BDGP R5/dm3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7227",
      "assemblyTaxId": "7227",
      "id": "dm2",
      "name": "Apr. 2004 (BDGP R4/dm2)",
      "label": "Fruit fly — Apr. 2004 (BDGP R4/dm2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "7227",
      "assemblyTaxId": "7227",
      "id": "dm1",
      "name": "Jan. 2003 (BDGP R3/dm1)",
      "label": "Fruit fly — Jan. 2003 (BDGP R3/dm1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ncbi",
      "taxId": "4932",
      "assemblyTaxId": "559292",
      "id": "GCF_000146045.2",
      "name": "R64",
      "label": "Budding yeast — S288C — R64 (GCF_000146045.2)",
      "organism": "Saccharomyces cerevisiae S288C",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/4932/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:28.287Z"
    },
    {
      "source": "ucsc",
      "taxId": "4932",
      "assemblyTaxId": "4932",
      "id": "sacCer2",
      "name": "June 2008 (SGD/sacCer2)",
      "label": "Budding yeast — June 2008 (SGD/sacCer2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "4932",
      "assemblyTaxId": "4932",
      "id": "sacCer1",
      "name": "Oct. 2003 (SGD/sacCer1)",
      "label": "Budding yeast — Oct. 2003 (SGD/sacCer1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ncbi",
      "taxId": "3702",
      "assemblyTaxId": "3702",
      "id": "GCF_000001735.4",
      "name": "TAIR10.1",
      "label": "Thale cress — TAIR10.1 (GCF_000001735.4)",
      "organism": "Arabidopsis thaliana",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/3702/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:29.408Z"
    },
    {
      "source": "ncbi",
      "taxId": "562",
      "assemblyTaxId": "511145",
      "id": "GCF_000005845.2",
      "name": "ASM584v2",
      "label": "E. coli — str. K-12 substr. MG1655 — ASM584v2 (GCF_000005845.2)",
      "organism": "Escherichia coli str. K-12 substr. MG1655",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/562/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:30.582Z"
    },
    {
      "source": "ncbi",
      "taxId": "562",
      "assemblyTaxId": "386585",
      "id": "GCF_000008865.2",
      "name": "ASM886v2",
      "label": "E. coli — O157:H7 str. Sakai — ASM886v2 (GCF_000008865.2)",
      "organism": "Escherichia coli O157:H7 str. Sakai",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/562/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:30.582Z"
    },
    {
      "source": "ensembl",
      "taxId": "9823",
      "assemblyTaxId": "9823",
      "id": "Sscrofa11.1",
      "name": "Sscrofa11.1",
      "species": "sus_scrofa",
      "label": "Pig — Sscrofa11.1",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/sus_scrofa?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:33.941Z"
    },
    {
      "source": "ncbi",
      "taxId": "9823",
      "assemblyTaxId": "9823",
      "id": "GCF_054392235.1",
      "name": "Sscrofa_HxYL_maternal_Yorkshire_Landrace_v2.0",
      "label": "Pig — Sscrofa_HxYL_maternal_Yorkshire_Landrace_v2.0 (GCF_054392235.1)",
      "organism": "Sus scrofa",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9823/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:31.630Z"
    },
    {
      "source": "ucsc",
      "taxId": "9823",
      "assemblyTaxId": "9823",
      "id": "susScr11",
      "name": "Feb. 2017 (Sscrofa11.1/susScr11)",
      "label": "Pig — Feb. 2017 (Sscrofa11.1/susScr11)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9823",
      "assemblyTaxId": "9823",
      "id": "susScr3",
      "name": "Aug. 2011 (SGSC Sscrofa10.2/susScr3)",
      "label": "Pig — Aug. 2011 (SGSC Sscrofa10.2/susScr3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9823",
      "assemblyTaxId": "9823",
      "id": "susScr2",
      "name": "Nov. 2009 (SGSC Sscrofa9.2/susScr2)",
      "label": "Pig — Nov. 2009 (SGSC Sscrofa9.2/susScr2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "bGalGal1.mat.broiler.GRCg7b",
      "name": "bGalGal1.mat.broiler.GRCg7b",
      "species": "gallus_gallus",
      "label": "Chicken — bGalGal1.mat.broiler.GRCg7b",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/gallus_gallus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:42.295Z"
    },
    {
      "source": "ncbi",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "GCF_016699485.2",
      "name": "bGalGal1.mat.broiler.GRCg7b",
      "label": "Chicken — bGalGal1.mat.broiler.GRCg7b (GCF_016699485.2)",
      "organism": "Gallus gallus",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9031/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:34.298Z"
    },
    {
      "source": "ucsc",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "GRCg7b",
      "name": "Jan. 2021 (GRCg7b/GCF_016699485.2)",
      "label": "Chicken — Jan. 2021 (GRCg7b/GCF_016699485.2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "galGal6",
      "name": "Mar. 2018 (GRCg6a/galGal6)",
      "label": "Chicken — Mar. 2018 (GRCg6a/galGal6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "galGal5",
      "name": "Dec 2015 (Gallus_gallus-5.0/galGal5)",
      "label": "Chicken — Dec 2015 (Gallus_gallus-5.0/galGal5)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "galGal4",
      "name": "Nov. 2011 (ICGSC Gallus_gallus-4.0/galGal4)",
      "label": "Chicken — Nov. 2011 (ICGSC Gallus_gallus-4.0/galGal4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "galGal3",
      "name": "May 2006 (WUGSC 2.1/galGal3)",
      "label": "Chicken — May 2006 (WUGSC 2.1/galGal3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9031",
      "assemblyTaxId": "9031",
      "id": "galGal2",
      "name": "Feb. 2004 (WUGSC 1.0/galGal2)",
      "label": "Chicken — Feb. 2004 (WUGSC 1.0/galGal2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ensembl",
      "taxId": "9940",
      "assemblyTaxId": "9940",
      "id": "ARS-UI_Ramb_v3.0",
      "name": "ARS-UI_Ramb_v3.0",
      "species": "ovis_aries",
      "label": "Sheep — ARS-UI_Ramb_v3.0",
      "status": "Annotation assembly at catalogue date",
      "url": "https://rest.ensembl.org/info/assembly/ovis_aries?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:43.713Z"
    },
    {
      "source": "ncbi",
      "taxId": "9940",
      "assemblyTaxId": "9940",
      "id": "GCF_016772045.2",
      "name": "ARS-UI_Ramb_v3.0",
      "label": "Sheep — ARS-UI_Ramb_v3.0 (GCF_016772045.2)",
      "organism": "Ovis aries",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9940/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:42.736Z"
    },
    {
      "source": "ucsc",
      "taxId": "9940",
      "assemblyTaxId": "9940",
      "id": "ARS_UI_Ramb_v2.0",
      "name": "Feb. 2021 (ARS-UI_Ramb_v2.0/GCF_016772045.1)",
      "label": "Sheep — Feb. 2021 (ARS-UI_Ramb_v2.0/GCF_016772045.1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9940",
      "assemblyTaxId": "9940",
      "id": "oviAri4",
      "name": "Nov. 2015 (Oar_v4.0/oviAri4)",
      "label": "Sheep — Nov. 2015 (Oar_v4.0/oviAri4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9940",
      "assemblyTaxId": "9940",
      "id": "oviAri3",
      "name": "Aug. 2012 (ISGC Oar_v3.1/oviAri3)",
      "label": "Sheep — Aug. 2012 (ISGC Oar_v3.1/oviAri3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "9940",
      "assemblyTaxId": "9940",
      "id": "oviAri1",
      "name": "Feb. 2010 (ISGC Ovis_aries_1.0/oviAri1)",
      "label": "Sheep — Feb. 2010 (ISGC Ovis_aries_1.0/oviAri1)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ncbi",
      "taxId": "6239",
      "assemblyTaxId": "6239",
      "id": "GCF_000002985.6",
      "name": "WBcel235",
      "label": "C. elegans — WBcel235 (GCF_000002985.6)",
      "organism": "Caenorhabditis elegans",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/6239/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:44.835Z"
    },
    {
      "source": "ucsc",
      "taxId": "6239",
      "assemblyTaxId": "6239",
      "id": "ce11",
      "name": "Feb. 2013 (WBcel235/ce11)",
      "label": "C. elegans — Feb. 2013 (WBcel235/ce11)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "6239",
      "assemblyTaxId": "6239",
      "id": "ce10",
      "name": "Oct. 2010 (WS220/ce10)",
      "label": "C. elegans — Oct. 2010 (WS220/ce10)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "6239",
      "assemblyTaxId": "6239",
      "id": "ce6",
      "name": "May 2008 (WS190/ce6)",
      "label": "C. elegans — May 2008 (WS190/ce6)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "6239",
      "assemblyTaxId": "6239",
      "id": "ce4",
      "name": "Jan. 2007 (WS170/ce4)",
      "label": "C. elegans — Jan. 2007 (WS170/ce4)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ucsc",
      "taxId": "6239",
      "assemblyTaxId": "6239",
      "id": "ce2",
      "name": "Mar. 2004 (WS120/ce2)",
      "label": "C. elegans — Mar. 2004 (WS120/ce2)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ncbi",
      "taxId": "4577",
      "assemblyTaxId": "4577",
      "id": "GCF_902167145.1",
      "name": "Zm-B73-REFERENCE-NAM-5.0",
      "label": "Maize — Zm-B73-REFERENCE-NAM-5.0 (GCF_902167145.1)",
      "organism": "Zea mays",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/4577/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:46.027Z"
    },
    {
      "source": "ncbi",
      "taxId": "511145",
      "assemblyTaxId": "511145",
      "id": "GCF_000005845.2",
      "name": "ASM584v2",
      "label": "E. coli K-12 MG1655 — ASM584v2 (GCF_000005845.2)",
      "organism": "Escherichia coli str. K-12 substr. MG1655",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/511145/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:47.018Z"
    },
    {
      "source": "ncbi",
      "taxId": "559292",
      "assemblyTaxId": "559292",
      "id": "GCF_000146045.2",
      "name": "R64",
      "label": "Yeast S288C — R64 (GCF_000146045.2)",
      "organism": "Saccharomyces cerevisiae S288C",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/559292/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:48.174Z"
    },
    {
      "source": "ucsc",
      "taxId": "559292",
      "assemblyTaxId": "559292",
      "id": "sacCer3",
      "name": "Apr. 2011 (SacCer_Apr2011/sacCer3)",
      "label": "Yeast S288C — Apr. 2011 (SacCer_Apr2011/sacCer3)",
      "status": "UCSC assembly; annotation tracks checked on retrieval",
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z"
    },
    {
      "source": "ncbi",
      "taxId": "224308",
      "assemblyTaxId": "224308",
      "id": "GCF_000009045.1",
      "name": "ASM904v1",
      "label": "B. subtilis 168 — ASM904v1 (GCF_000009045.1)",
      "organism": "Bacillus subtilis subsp. subtilis str. 168",
      "status": "RefSeq reference at catalogue date",
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/224308/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:49.240Z"
    }
  ],
  "services": [
    {
      "id": "ncbi",
      "name": "NCBI",
      "homepage": "https://www.ncbi.nlm.nih.gov/",
      "documentation": "https://www.ncbi.nlm.nih.gov/datasets/docs/v2/",
      "get": [
        "gene",
        "nucleotide",
        "protein",
        "annotations",
        "assembly"
      ],
      "send": []
    },
    {
      "id": "uniprot",
      "name": "UniProt",
      "homepage": "https://www.uniprot.org/",
      "documentation": "https://www.uniprot.org/help/api",
      "get": [
        "protein"
      ],
      "send": []
    },
    {
      "id": "ensembl",
      "name": "Ensembl",
      "homepage": "https://www.ensembl.org/",
      "documentation": "https://rest.ensembl.org/",
      "get": [
        "gene",
        "nucleotide",
        "protein",
        "annotations"
      ],
      "send": [
        "region",
        "variant"
      ]
    },
    {
      "id": "ucsc",
      "name": "UCSC Genome Browser",
      "homepage": "https://genome.ucsc.edu/",
      "documentation": "https://genome.ucsc.edu/goldenPath/help/api.html",
      "get": [
        "nucleotide",
        "protein",
        "annotations"
      ],
      "send": [
        "region",
        "variant"
      ]
    },
    {
      "id": "ena",
      "name": "ENA",
      "homepage": "https://www.ebi.ac.uk/ena/browser/",
      "documentation": "https://www.ebi.ac.uk/ena/browser/api/",
      "get": [
        "nucleotide"
      ],
      "send": []
    },
    {
      "id": "rcsb",
      "name": "RCSB PDB",
      "homepage": "https://www.rcsb.org/",
      "documentation": "https://search.rcsb.org/",
      "get": [
        "structure"
      ],
      "send": [
        "structure"
      ]
    },
    {
      "id": "alphafold",
      "name": "AlphaFold DB",
      "homepage": "https://alphafold.ebi.ac.uk/",
      "documentation": "https://alphafold.ebi.ac.uk/faq",
      "get": [
        "structure"
      ],
      "send": [
        "structure"
      ]
    },
    {
      "id": "blast",
      "name": "NCBI BLAST",
      "homepage": "https://blast.ncbi.nlm.nih.gov/",
      "documentation": "https://blast.ncbi.nlm.nih.gov/doc/blast-help/",
      "get": [],
      "send": [
        "similar"
      ]
    },
    {
      "id": "primer",
      "name": "NCBI Primer-BLAST",
      "homepage": "https://www.ncbi.nlm.nih.gov/tools/primer-blast/",
      "documentation": "https://www.ncbi.nlm.nih.gov/tools/primer-blast/primerinfo.html",
      "get": [],
      "send": [
        "primers"
      ]
    },
    {
      "id": "gdv",
      "name": "NCBI Genome Data Viewer",
      "homepage": "https://www.ncbi.nlm.nih.gov/gdv/",
      "documentation": "https://www.ncbi.nlm.nih.gov/genome/gdv/browser/help/",
      "get": [],
      "send": [
        "region",
        "variant"
      ]
    },
    {
      "id": "proksee",
      "name": "Proksee",
      "homepage": "https://proksee.ca/",
      "documentation": "https://proksee.ca/help",
      "get": [],
      "send": [
        "genome"
      ]
    },
    {
      "id": "interpro",
      "name": "InterPro",
      "homepage": "https://www.ebi.ac.uk/interpro/",
      "documentation": "https://www.ebi.ac.uk/interpro/help/",
      "get": [],
      "send": [
        "protein"
      ]
    },
    {
      "id": "hmmer",
      "name": "HMMER",
      "homepage": "https://www.ebi.ac.uk/Tools/hmmer/",
      "documentation": "https://www.ebi.ac.uk/Tools/hmmer/help",
      "get": [],
      "send": [
        "protein"
      ]
    },
    {
      "id": "clustalo",
      "name": "Clustal Omega",
      "homepage": "https://www.ebi.ac.uk/Tools/msa/clustalo/",
      "documentation": "https://www.ebi.ac.uk/Tools/msa/clustalo/help/",
      "get": [],
      "send": [
        "align"
      ]
    },
    {
      "id": "foldseek",
      "name": "Foldseek",
      "homepage": "https://search.foldseek.com/",
      "documentation": "https://github.com/steineggerlab/foldseek",
      "get": [],
      "send": [
        "structure"
      ]
    },
    {
      "id": "dbsnp",
      "name": "dbSNP",
      "homepage": "https://www.ncbi.nlm.nih.gov/snp/",
      "documentation": "https://www.ncbi.nlm.nih.gov/snp/docs/",
      "get": [],
      "send": [
        "variant"
      ]
    },
    {
      "id": "clinvar",
      "name": "ClinVar",
      "homepage": "https://www.ncbi.nlm.nih.gov/clinvar/",
      "documentation": "https://www.ncbi.nlm.nih.gov/clinvar/docs/",
      "get": [],
      "send": [
        "variant"
      ]
    },
    {
      "id": "gnomad",
      "name": "gnomAD",
      "homepage": "https://gnomad.broadinstitute.org/",
      "documentation": "https://gnomad.broadinstitute.org/help",
      "get": [],
      "send": [
        "variant"
      ]
    }
  ],
  "evidence": [
    {
      "url": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=taxonomy&id=9606,10090,10116,9913,9615,7955,7227,4932,3702,562,9823,9031,9940,6239,4577,511145,559292,224308&retmode=json",
      "checkedAt": "2026-10-08T01:36:05.958Z",
      "sha256": "af04bdc909955404e631fd78848a21910effe7f0bb265ca5759e7717231f1a5c"
    },
    {
      "url": "https://rest.ensembl.org/info/species?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:08.565Z",
      "sha256": "15ca46142fe2140bd212ce72b74f05223426aa8004975ea4f18db95030da80c2"
    },
    {
      "url": "https://api.genome.ucsc.edu/list/ucscGenomes",
      "checkedAt": "2026-10-08T01:36:08.884Z",
      "sha256": "a88339bc7d00816995ee40332dfeaec836d06261cb074c7703b7d260ca93fd0b"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9606/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:10.165Z",
      "sha256": "8c34eddba3c3873c5d6589db9efae52613f43647ff61e997d54950bca8ff0f0f"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/homo_sapiens?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:11.455Z",
      "sha256": "8c3f035bf4a5ea90af98730335f3f60d82929da36aa3dde91276844134180487"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/10090/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:12.065Z",
      "sha256": "4dc3bf791be5a90d697a4581c6c24fbeb8eaa98445ce071574cd41a00528183e"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/mus_musculus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:16.972Z",
      "sha256": "3d4403d94a9763b426447af6f549987e4c8517bd98c1dbf2fbcd3596053ae674"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/10116/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:17.560Z",
      "sha256": "3c7733efc0beae49d08dbe66a5fd795e253796a65ec4f303193144cfcc74a998"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/rattus_norvegicus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:18.378Z",
      "sha256": "9f09c055f8ee75234fe4b6615ca8733b2f8378b7d0958a80b2aa1cd543726b79"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9913/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:19.571Z",
      "sha256": "6cf00820b0b80cc8fe166966ff507696565e053502c4dd90c84ec0e9c3881ff9"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/bos_taurus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:22.186Z",
      "sha256": "18924d83a9f67046eb0178aa847a9dd6c62b270450fbffd3be50844df2ba81e8"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9615/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:22.589Z",
      "sha256": "f9eda22576d4cfe21ffeb88e0ba5ccbc3683e4ed9363880fbf96c7de9515ee4f"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/canis_lupus_familiaris?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:24.682Z",
      "sha256": "9c80bc067ef446bb54de58cdb30152e1156352cc48f793fa7c75d09e1a1841b0"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/7955/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:24.982Z",
      "sha256": "f1249c5521f46acea12b5542dd4e5f5e16e31d23d8c3ad1289e174c0174898ae"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/danio_rerio?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:26.706Z",
      "sha256": "565e1fe086a7567e45cc2f2f5c2d54147105ce33dde91b1d46fef2aa30f77c54"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/7227/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:27.197Z",
      "sha256": "6f434c56a0fe07bc362d4663dcf67814e480df1c7e1a41a2e8968f41532182b7"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/4932/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:28.287Z",
      "sha256": "eea3ad4615328e7cf871868e85cc305c5e836ee8d4be4b37ba85b8be6d85b926"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/3702/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:29.408Z",
      "sha256": "10e7d7ca7ef4e4bc3a6d4e178aab7813988bf60a048cff4f62f595d14ea0ea40"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/562/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:30.582Z",
      "sha256": "afaa9427c5bb197ab0a433c70954e827a42e46dcdf114c26c847b796fb696f0b"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9823/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:31.630Z",
      "sha256": "ac5a7fa116e161e6f24d56b0b6319373380120c9a598019801f9f6f7a99e7966"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/sus_scrofa?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:33.941Z",
      "sha256": "8d327c771924946dd39d0c60589c8ce79ce6a8fd3630230c6efa5326d4c8f9a3"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9031/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:34.298Z",
      "sha256": "10ad8f0557b1593364c234559be043451a2c6915419b61c41107a9d8d1c71b2f"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/gallus_gallus?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:42.295Z",
      "sha256": "84e3586b07f8312b5b22f5de61c595169920280a65926097ee054af1fd8fdc44"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/9940/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:42.736Z",
      "sha256": "d0922df1579fde21f163229f379f8a1f87248dbf331fde7349dd701df6420dbb"
    },
    {
      "url": "https://rest.ensembl.org/info/assembly/ovis_aries?content-type=application/json",
      "checkedAt": "2026-10-08T01:36:43.713Z",
      "sha256": "70797951aab6b655a114300176c625e96990e4ec16cd906e6bc1a3d1bcce0641"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/6239/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:44.835Z",
      "sha256": "91af19052ffaba68b3b30aecf393bb07d8a5a38b8d2089b394e4272aa736f0da"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/4577/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:46.027Z",
      "sha256": "5308f0a54f0dc5c3d56a5539ee9639a79f7c6c47eb877b1e4f3cdf0fb0d6cb6e"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/511145/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:47.018Z",
      "sha256": "e0d7e165dda7acab416ca4e2d393c204a79deac0f2268b7d243c6323d4287849"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/559292/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:48.174Z",
      "sha256": "eea3ad4615328e7cf871868e85cc305c5e836ee8d4be4b37ba85b8be6d85b926"
    },
    {
      "url": "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/taxon/224308/dataset_report?filters.reference_only=true&page_size=100",
      "checkedAt": "2026-10-08T01:36:49.240Z",
      "sha256": "db3753c95d9fa9ac100871c5a05333e2d0d16d476a21235adea0e6b09ed3ead2"
    }
  ]
};
