export const DNA_VIEWER_SEARCH_RESULT_LIMIT = 1_000;
export const PROTEIN_STRUCTURE_SEARCH_SUGGESTION_LIMIT = 80;
export const PROTEIN_STRUCTURE_NEAREST_ATOM_PICK_LIMIT = 12_000;
export const PROTEIN_STRUCTURE_KEYBOARD_INSPECTION_LIMIT = 2_000;
export const PROTEIN_STRUCTURE_SUGGESTION_CHAR_LIMIT = 1_500_000;
